Vagrant.configure("2") do |config|
  # Configuration commune à toutes les machines
  config.vm.box = "b2-tp2-centos"

  # Config une première VM "node1"
  config.vm.define "node1" do |node1|
    # remarquez l'utilisation de 'node1.' défini sur la ligne au dessus
    node1.vm.network "private_network", ip: "192.168.56.21"

    # Exécution d'un script au démarrage de la VM
    node1.vm.provision "shell", path: "script.sh"

    node1.vm.hostname = "node1.tp2.b2"

    node1.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
    node1.vm.provider :virtualbox do |vb|
      vb.name = "node1"
    end
  end

  # Config une première VM "node2"
  config.vm.define "node2" do |node2|
    
    # remarquez l'utilisation de 'node2.' défini sur la ligne au dessus
    node2.vm.network "private_network", ip: "192.168.56.22"
    
    # Exécution d'un script au démarrage de la VM
    node2.vm.provision "shell", path: "script.sh"
    node2.vm.hostname = "node2.tp2.b2"
  
    node2.vm.provider "virtualbox" do |v|
      v.memory = 512
    end
    node2.vm.provider :virtualbox do |vb|
      vb.name = "node2"
    end
  end
end

 
