  
Vagrant.configure("2")do|config|
  config.vm.box="centos/8"
  

  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.provider :virtualbox do |vb|
    vb.name = "node1"
    vb.memory = 1024
  end

  # Exécution d'un script au démarrage de la VM
  config.vm.provision "shell", path: "scripts/script.sh"

  config.vm.hostname = "node1.tp3.b2"

  config.vm.network "private_network", ip: "192.168.2.31"

 
