Vagrant.configure("2") do |config|

  # Configuration commune à toutes les machines
  config.vm.box = "b2-tp2-centos"

  # Config une première VM "node1"
  config.vm.define "node1" do |node1|
    # remarquez l'utilisation de 'node1.' défini sur la ligne au dessus
    node1.vm.network "private_network", ip: "192.168.2.21"
    node1.vm.hostname = "node1.tp2.b2"
    node1.vm.provider :virtualbox do |vb|
      vb.name = "node1"
      vb.memory = 1024
    end

    # Exécution d'un script au démarrage de la VM
    node1.vm.provision "shell", path: "script_node1.sh"
  end

  # Config une première VM "node2"
  config.vm.define "node2" do |node2|
    # remarquez l'utilisation de 'node2.' défini sur la ligne au dessus
    node2.vm.network "private_network", ip: "192.168.2.22"
    node2.vm.hostname = "node2.tp2.b2"
    node2.vm.provider :virtualbox do |vb|
      vb.name = "node2"
      vb.memory = 512
    end
  
    # Exécution d'un script au démarrage de la VM
    node2.vm.provision "shell", path: "script_node2.sh"
  end
end
